import Btn from "@/components/button";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>hello there</h1>
        <Btn/>
        {children}
      </body>
    </html>
  );
}
